app:
  random: ${random.uuid}


hello:
  case-type: camel
  position: 1
  greeting: 'Bye'
  style: uppercase
  
logging:
  level:
    root: WARN
    '[org.springframework.boot]': debug
---
spring:
  config:
    activate:
      on-profile: prod

logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
  file:
    name: server.log
    path: .
    

hello:
  greeting: 'Biééén le Bjour '

server:
  port: 8000