spring:
  jpa:
    show-sql: true
    open-in-view: false    

  security:
    user:
      password: secret

management:
  endpoints:
    web:
      exposure:
        include: '*'
  auditevents:
    enabled: true
  endpoint:
    health:
      show-details: always
appli:
  secretKey: azerty
  validity: 10000
  rememberMe: 10000
        
logging:
  level:
    '[org.springframework.security]': debug    
--- 
spring:
  config:
    activate:
      on-profile:
      - prod
      
  datasource:
    url: jdbc:postgresql://localhost:5434/f_members
    username: postgres
    password: postgres
    
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 2000
    
  jpa:
    hibernate:
      ddl-auto: validate
    
    
