version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: f_members
    ports:
      - "5435:5432"
    restart: unless-stopped
  
  spring:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/f_members
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

