spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: import.sql

logging:
  level:
    org.springframework.transaction: debug
---
spring:
  profiles: prod

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5434/f_members
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      connection-timeout: 20000 