spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          import_files: import.sql

    open-in-view: false

logging:
  level:
#    org.springframework.transaction: debug
    org.springframework.security: debug


appli:
  secretKey: secret
  validity: 1000
  rememberMe: 1000

---
spring:
  profiles: prod

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5434/f_members
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      connection-timeout: 20000 

---
spring:
  profiles:
    oauth
    
  security:
    oauth2:
      client: 
        registration: 
          github:
            client-id: 65400b28079173786879
            client-secret: b354d87a852b421b82a87094b8317da0d646aeb3